# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff70ff8c0f4dd43bc9bfde94b010576e65e32958634dbee49c5c21f7ec240ba5d873ef8ec1989babc88f60b51a2096713e8dfdfcbe54cfecc7d79e9a4ade0fa1

test:
  secret_key_base: 264358ea2b469adbf66e53f58eb2955959bfbb9a0351aadae567ae18959a1e5b1bf92d6dd41d46939fb984d7e5cc8eebcaef42540dfe81c418c50c454202a1e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
